apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "graphhopper-service.fullname" . }}
  labels:
    {{- include "graphhopper-service.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "graphhopper-service.selectorLabels" . | nindent 6 }}
  strategy: {}
  template:
    metadata:
      annotations:
        ad.datadoghq.com/graphhopper-service.checks: |
          {
            "openmetrics": {
              "instances": [
                {
                  "openmetrics_endpoint": "http://%%host%%:%%port%%/metrics",
                  "metrics": [
                    "jvm_*",
                    "process_*"
                    "system_*"
                  ]
                }
              ]
            }
          }
      labels:
        {{- include "graphhopper-service.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: graphhopper-service
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.awsAccount }}.dkr.ecr.{{ .Values.region }}.amazonaws.com/graphhopper-service:{{ include "graphhopper-service.appVersion" . }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        lifecycle: 
          preStop:
            exec:
              command: ["/bin/sh", "-c" , "sleep 30"]
        readinessProbe:
          httpGet:
            path: /health
            port: 8989
          failureThreshold: 5
          periodSeconds: 2
          initialDelaySeconds: 30
        volumeMounts:
        - mountPath: /graphhopper/data
          name: s3-filesystem
      volumes:
      - name: s3-filesystem
        persistentVolumeClaim:
          claimName: graphhopper-service              

