image:
  pullPolicy: Always
  tag: "graphhopper-service"

replicaCount: 1

autoscaling:
  enabled: true
  minReplicas: 4
  maxReplicas: 8
  targetCPUUtilizationPercentage: 80

resources:
  limits:
    memory: 12G
  requests:
    cpu: "0.5"
    memory: 12G

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
    
podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 8989

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: graphhopper-service.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []


nodeSelector: {}

tolerations: []

affinity: {}

additionalVolumeMounts: {}
